version: '2.27.1'

services:
  db:
    image: 'bitnami/mongodb:latest'
    ports:
      - 27018:27017
    restart: on-failure
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - ALLOW_EMPTY_PASSWORD=yes
      # - MONGO_INITDB_DATABASE: api_tdd
