# Generated by Django 5.0.1 on 2024-01-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
